version: '3.8'

services:
  backend:
    build:
      context: ./apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - DJANGO_SETTINGS_MODULE=wealthwise.settings
    volumes:
      - ./apps/backend:/app
      - /app/__pycache__
    depends_on:
      - db
    networks:
      - wealthwise-network

  frontend:
    build:
      context: ./apps/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:8000
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - backend
    networks:
      - wealthwise-network

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=wealthwise
      - POSTGRES_USER=wealthwise
      - POSTGRES_PASSWORD=wealthwise
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - wealthwise-network

volumes:
  postgres_data:

networks:
  wealthwise-network:
    driver: bridge