# Generated by Django 4.1.13 on 2025-06-02 00:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nama/deskripsi token (misal: Batch Alpha Tester, Internal Team, dll)', max_length=100)),
                ('token_code', models.CharField(help_text='Kode token unik yang akan digunakan untuk registrasi', max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Status token - hanya token aktif yang bisa digunakan untuk registrasi')),
                ('max_usage', models.PositiveIntegerField(default=1, help_text='Maksimal berapa kali token ini bisa digunakan (0 = unlimited)')),
                ('current_usage', models.PositiveIntegerField(default=0, help_text='Berapa kali token ini sudah digunakan')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Tanggal kadaluarsa token (kosongkan jika tidak ada)', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_by', models.CharField(blank=True, help_text='Siapa yang membuat token ini', max_length=100)),
                ('notes', models.TextField(blank=True, help_text='Catatan tambahan tentang token ini')),
            ],
            options={
                'verbose_name': 'Registration Token',
                'verbose_name_plural': 'Registration Tokens',
                'db_table': 'reg_tokens',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='reg_token',
            field=models.ForeignKey(blank=True, help_text='Token registrasi yang digunakan untuk mendaftar', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registered_users', to='master.regtoken'),
        ),
    ]
