# Generated by Django 5.2 on 2025-04-24 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=50)),
                ('endpoint_url', models.URLField(blank=True, null=True)),
                ('asset_type', models.CharField(choices=[('stock', 'Stock'), ('crypto', 'Crypto'), ('bonds', 'Bonds')], default='stock', max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('last_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('price_check', models.BooleanField(default=False)),
                ('deviden_check', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('type', models.CharField(choices=[('stock', 'Stock'), ('bonds', 'Bonds'), ('crypto', 'Crypto'), ('other', 'Other')], default='stock', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Sekuritas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('type', models.CharField(choices=[('interim', 'Interim'), ('final', 'Final')], default='final', max_length=10)),
                ('status', models.CharField(choices=[('predict', 'Predict'), ('scheduled', 'Scheduled'), ('fix', 'Fix')], default='predict', max_length=10)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='journal.asset')),
            ],
        ),
        migrations.AddField(
            model_name='asset',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='journal.sector'),
        ),
    ]
