# Generated by Django 4.1.13 on 2025-06-01 01:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmenttransaction',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_transactions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentportfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_portfolios', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='investmentholding',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='invest.asset'),
        ),
        migrations.AddField(
            model_name='investmentholding',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='invest.investmentportfolio'),
        ),
        migrations.AddField(
            model_name='investmentholding',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment_holdings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assetprice',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='invest.asset'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['user', 'transaction_date'], name='investment__user_id_65fa0d_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['portfolio', 'transaction_date'], name='investment__portfol_3239b1_idx'),
        ),
        migrations.AddIndex(
            model_name='investmenttransaction',
            index=models.Index(fields=['asset', 'transaction_date'], name='investment__asset_i_3335a9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='investmentholding',
            unique_together={('user', 'portfolio', 'asset')},
        ),
        migrations.AddIndex(
            model_name='assetprice',
            index=models.Index(fields=['asset', 'timestamp'], name='asset_price_asset_i_4e40a8_idx'),
        ),
    ]
