name: finance_track
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  # State Management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  # Network
  dio: ^5.3.2
  # Local Storage
  sqflite: ^2.3.0
  shared_preferences: ^2.2.1
  flutter_secure_storage: ^9.0.0
  # UI Components
  fl_chart: ^0.63.0
  flutter_svg: ^2.0.7
  intl: ^0.18.1
  # Biometrics
  local_auth: ^2.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
